### ISSUE TITLE
MongoDB 2.6 issues

### ISSUE THREAD

**Issue by rwillmer** [meteor/meteor#2036]
*@rwillmer's original issue text has been moved to a quote in the first comment.*

Work necessary to support Mongo 2.6:
- [x] Build dev bundle with Mongo 2.6
- [x] Update [oplog documentation](https://github.com/meteor/meteor/issues/2036#issuecomment-40149867)
- [x] Avoid querying system.replset #2121
- [x] Upsert issue #2278
- [x] Code review for upsert issue #2278 http://phabricator.meteor.io/D25
- [ ] Maybe avoid the simulated upsert if we know we're on 2.6?
- [x] `$near` issue (probably already fixed?) #3604
- [x] Double-check "Remove Method Signature Change"
- [x] ensure all tests pass
- [x] Test that changes work on non-oplog Mongo 2.4
- [x] Test that changes work on oplog Mongo 2.4
- [x] Drop --nohttpinterface if it is no longer necessary
- [x] History.md updates
- [ ] Once merged, close #2163

Note: Mongo 3.0 will be out soon, but I'd rather target stable releases than prereleases. Based on the current Mongo 3.0 release notes, it will be a pretty smooth update; the main thing we'll need to do is upgrade our version of the Node Mongo driver.

**Comment by LarsBuur** [comment]
We just deployed a replica set on mongodb 2.6.6 using https://mms.mongodb.com. 

Adding a oplogger role with specific find rights to "local.system.replset" and "local.AnyCollection" and then creating a new user with that role did the job. 

The interface in mms is a little strange with regards to setting permissions to a specific collections but it is possible.

**Comment by meawoppl** [comment]
It would also be useful to have information floating around about Meteor Version <-> Mongo Version in some sensible form.

**Comment by glasser** [comment]
Well, we do try to document the version that we ship with Meteor (and we test against) in History.md at least.

**Comment by glasser** [comment]
note to self: may not need to disable http interface any more

**Comment by glasser** [comment]
and look into "Remove Method Signature Change" (although that matches what we do already)

**Comment by glasser** [comment]
See also #3604

**Comment by glasser** [comment]
See also #2163

**Comment by glasser** [comment]
devel now ships with MongoDB 2.6.7. The few aspects of Meteor which were not already 2.6-compatible are now 2.6-compatible.

The [oplog observe driver instructions on the wiki](https://github.com/meteor/meteor/wiki/Oplog-Observe-Driver) have been updated.  Note that at @arunoda's suggestion (see #2121) you no longer need a special role that can access `system.replset`, so using upcoming versions of Meteor with MongoDB 2.6 will not require the user-defined role that @rwillmer helpfully explained above.  (However, you still need that special role for 1.0.3.1 and older with 2.6.)

We are still using an old version of the Node Mongo driver which does not support the current-unreleased MongoDB 3.0.  Hopefully will fix this before the next release, depending on time; that is being tracked separately in #3654.

**Comment by dandv** [comment]
Really excited about Mongo 3.0:

> MongoDB 3.0 will be generally available in early March. The new release will expand the use cases for MongoDB, allowing you to use the database for the vast majority of new applications. We’re making major improvements that have a big impact: write performance has improved by 7x - 10x, compression reduces storage needs by up to 80%, and new management software called Ops Manager will reduce operational overhead by 95% for most tasks. MongoDB 3.0 dramatically improves your ability to deliver apps to market faster and more efficiently than ever before.

**Comment by seiyria** [comment]
How will meteor play with mongo 3.0 by default?

**Comment by emgee3** [comment]
Document-level locking which comes in 3.0 will handle the massive performance problems that I'm having in one of my apps. Really hoping 3.0 support lands sooner than later.

**Comment by glasser** [comment]
I think the last few commenters failed to read my last comment, which explained the current support level of 3.0 and pointed at a different issue for it. This issue is about 2.6.

**Comment by JeremySaks** [comment]
Is there a way to enable oplog support for Meteor 1.0.4.1 + Mongo 2.6.8 for a remote host (Compose) that does not allow access to the /admin db? That's the issue I hit today while trying to deploy with Compose running Mongo 2.6.8.

Deployment fails with the oplog user I previously created for use with 2.4 with the message:
```
MongoError: not authorized for query on local.oplog.rs
```
Compose support told me today that `/admin access isn't provided to any MongoDB deployment that we host.` And trying `db.createUser()` in the shell of /myApp with `roles: [{role: "read", db: "local"}]` fails with
```
Error: couldn't add user: not authorized on myApp to execute command { createUser [...] }
```
As far as I can tell the Meteor oplog wiki doesn't address this scenario and I'm not sure how to move forward with oplog support under this configuration, which I think is a common one.

**Comment by Slava** [comment]
@JeremySaks you probably want to ask this from your database hosting provider (compose in this case), here is a link to their docs about oplog: https://docs.compose.io/common-questions/getting-oplog-access.html

**Comment by JeremySaks** [comment]
Thank you @Slava - I do have a ticket in with them which I am hoping they respond to!

The issue specifically is that adding users with oplog access is permitted from their /app dbs but not from their /admin db, which now sounds like a prerequisite to enable oplog support with Meteor and Mongo 2.6. If I am reading the 1.0.4 release notes correctly this is the only way to get oplog support using Mongo 2.6. I was hoping to see if anyone has another strategy.

**Comment by glasser** [comment]
Are you sure that this is a difference between 2.4 and 2.6?  The oplog is in the `/local` db, and I'm pretty sure that adding users to any non-admin db is not going to give you permissions on `/local`.

**Comment by JeremySaks** [comment]
As far as I know I had never created a user in /local.  With 2.4 I created a user in /myApp and deployed `MONGO_OPLOG_URL` with the flag `capital.3.mongolayer.com:11111/local?authsource=myApp`.

That worked fine until yesterday, but with Mongo 2.6 apparently it no longer works. The passage I am looking at from the wiki https://github.com/meteor/meteor/wiki/Oplog-Observe-Driver that seems to highlight the change is here:
```
(You may be used to running db.createUser (or db.addUser) inside the actual database that you want the new user to be able to access (in this case, local), instead of running it in admin and using the authSource flag to specify that you want to authenticate against admin. However, this doesn't work with the special case of the local database. Mongo 2.6 specifically prevents you from creating users in the local database, and while Mongo 2.4 would let you do it, you would find that you need to run db.addUser separately against each database replica (and risking ending up with different passwords on each), because the local database is not itself replicated across servers.)
```

**Comment by JeremySaks** [comment]
Update: I was able to get things working without /admin access, it just required changing the authorizations to new users created with 2.6. Sorry for any confusion.

**Comment by voidale** [comment]
@JeremySaks how did you solve this?

**Comment by JeremySaks** [comment]
@voidale I was able to solve by creating two new db users post-upgrade to 2.6 (one as admin and one as oplog reader). I never created any in /local, before or after. I've pasted below the two user configurations from Compose both before and after the upgrade so you can see how they differ. I hope this is helpful.

#### Pre-Upgrade (v2.4, will not work in 2.6+)
`{ _id: "myDb.admin", user: "admin", db: "myDb", roles: [ { role: "dbOwner", db: "myDb" } ] }`
`{ _id: "myDb.oplogger", user: "oplogger", db: "myDb", roles: [ { role: "read", db: "myDb" } ] }`

#### Post-Upgrade (v2.6)
`{ _id: "myDb.primary", user: "primary", db: "myDb", roles: [ { role: "readWrite", db: "myDb" }, { role: "readonlyCluster", db: "admin" } ] }`
`{ _id: "myDb.readoplog", user: "readoplog", db: "myDb", roles: [ { role: "read", db: "myDb" }, { role: "readonlyCluster", db: "admin" } ] }`
