### ISSUE TITLE
Release 1.0.2

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3285]
This issue tracks the release of Meteor 1.0.2.  Have any concerns?  Mention them here.  Finding that the RCs are working great?  Mention that here.  We will keep this top-level description updated with known issues.

The current RC is `1.0.2-rc.7`.  Update your apps to the RC with `meteor update --release 1.0.2-rc.7`.  If you had set the `METEOR_OFFLINE_CATALOG` environment variable previously in order to work around previous performance issues, please stop setting it.

The focus of this release is [command-line tool performance and stability](https://github.com/meteor/meteor/milestones/Tool%20Performance%20and%20Stability), plus the `meteor shell` command.

Known issues:
- [x] History.md rough draft: https://github.com/meteor/meteor/blob/release-1.0.2/History.md
- [x] History.md final draft
- [ ] Still hoping to improve rebuild time for packages with npm deps #3279
- [x] Still hoping to remove self-test dependencies from the published tool [done in rc.6]
- [x] Cordova builds don't work [fixed in rc.2]
- [x] File change detection broken on Vagrant #3284 [partially fixed in rc.5 and rc.6, fully fixed in rc.7]
- [x] Reloads get slower over time? https://github.com/meteor/meteor/issues/2846#issuecomment-66792234
- [x] TypeError: Cannot read property 'version' of undefined https://github.com/meteor/meteor/issues/3285#issuecomment-66802301  [Believed fixed in rc.4]
- [ ] springboard does not refresh catalog if it knows about the release but not about the build. This is not a regression from 1.0. Workaround: 'meteor refresh' first.  #3317
- [x] Too many `*`s in `meteor list` when running from prerelease.  [not actually a bug]
- [x] safe-pathwatcher.testDirectory throws if `.meteor/local` does not exist yet  [fixed in rc.6]
- [ ] sessions fact can be negative:  https://github.com/meteor/meteor/issues/3285#issuecomment-67368681 [no consistent reproduction]
- [ ] client refresh when editing (but not saving) files in vim: #3322  [cannot reproduce]

RC history:
- `1.0.2-rc.1`: initial release candidate
- `1.0.2-rc.2`: fix failure to run Cordova builds
- `1.0.2-rc.3`: hopefully fix "Cannot read property 'version' of undefined" error
- `1.0.2-rc.4`: [mistakes made in the release process, DO NOT USE]
- `1.0.2-rc.5`: File watching should work on NFS, Vagrant shared folders, and other non-traditional filesystems.  [Though not in a common Vagrant use case; will be fixed in a later RC.]
- `1.0.2-rc.6`:
  - pathwatcher improvements: work better under Vagrant; print a message at the debug level; more tests
  - clear various tokens on password change
  - more validation of update methods
  - remove self-test support from built tool (shrink size of tool download)
  - implement soft refresh (#3213); should stop reloads from getting slower over time
- `1.0.2-rc.7`: Pathwatcher finally should work on Vagrant vboxsf with no extra configuration. Also fix a typo in `meteor login` output.

**Comment by jhorn3** [comment]
How do you unset  METEOR_OFFLINE_CATALOG  if it says "unset" isn't a command?

**Comment by Slava** [comment]
@jhorn3 `unset` is a command in bash. This might work differently depending on the shell you are using. If you are using some non-standard shell (like fish-shell, for example), look at the shell's docs.
