### ISSUE TITLE
Release 1.0.2.1

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3338]
This issue tracks the release of Meteor 1.0.2. Have any concerns? Mention them here. Finding that the RCs are working great? Mention that here. We will keep this top-level description updated with known issues.

This is a patch release for 1.0.2 which makes a few targeted changes to improve regressions introduced in 1.0.2.

The main fix in this release is about the file watching that the app runner does while you run apps, so testing running your apps, editing files, etc would be appreciated.

The current RC is `1.0.2.1-rc.2`. Update your apps to the RC with `meteor update --release 1.0.2.1-rc.2`.

Known issues
- [x] Typo in `meteor shell` output: beaf067
- [x] `test-packages packages/*` should not fail if some packages have no tests: 00a7da3
- [x] docs header improvement: 508472e
- [x] file watcher crash (should catch this error): f5f136ad
- [ ] file watcher slow on NFS?  CPU loop for many seconds?  Can't reproduce #3335
- [ ] file watcher doesn't reload on `less` file changes?  or just a race condition around saving two things quickly? on NFS? maybe it's the 1-second-resolution issue.  #3335
- [x] Need to make the wiki page linked from the #3336 message: https://github.com/meteor/meteor/wiki/File-Change-Watcher-Efficiency

RC history:
- `1.0.2.1-rc.1`: initial release candidate
- `1.0.2.1-rc.2`: If inotify fails on Linux in a detectable and fixable way, print a link to https://github.com/meteor/meteor/wiki/File-Change-Watcher-Efficiency
