### ISSUE TITLE
Release 1.0.4

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3814]
This issue tracks the release of Meteor 1.0.4. Have any concerns? Mention them here. Finding that the RCs are working great? Mention that here. We will keep this top-level description updated with known issues.

The current RC is `1.0.4-rc.6`. Update to the release candidate with: `meteor update --release 1.0.4-rc.6`

Read [the release notes](https://github.com/meteor/meteor/blob/release-1.0.4/History.md) to learn what's new in this release.  Highlights: MongoDB 2.6, a host of mongo-related bugfixes and optimizations, template-level subscriptions, DDP compression, Cordova upgrades, and more!  Prerelease docs are at https://docs-104rc.meteor.com/

- [x] Make sure switching between Mongo 2.6 and Mongo 2.4 doesn't fail in run-mongo #3692
- [x] New Session.set syntax is undocumented
- [x] New Session.set syntax is buggy #3849
- [ ] infinite rebuild cycle on `--settings dir` #3854 (probably a 1.0.2 regression)
- [x] flaky template-level subs test #3859
- [x] LocalCollection paused flag performance boost https://rbcommons.com/s/meteor/r/4/
- [x] evaluate if any packages need a minor/major version boost
- [x] direct access to npm https://rbcommons.com/s/meteor/r/13/
- [ ] bulk inserts #1255
- [x] permessage-deflate
- [x] See if it supports MongoDB 3.0 out of the box.
- [x] History.md initial pass
- [x] History.md final draft
- [x] mailmap update
- [x] license check
- [x] `self-test --slow`
- [x] full QA
- [x] all text ready
- [x] deploy troposphere with rc and profile full sync time [not happening -- reverted websocket change]
- [x] Review the Template.currentData/Template.parentData change
- [x] Track down DDP corruption from websocket compression
- [x] Cordova run-ios fails
- [x] Cordova issues

RC history:
* `1.0.4-rc.6`:
  * Revert multiple-colon validation from rc 4 (but keep leading/trailing validation, and apply it at `create --package` time still)
  * Move licenses into a subdirectory.
* `1.0.4-rc.5`:
  * Fixes running Cordova apps on Android emulators.
* `1.0.4-rc.4`:
  * Style cleanup to `setPassword` change
  * Validate that package names contain at most one colon which cannot be at the beginning or end.
* `1.0.4-rc.3`:
  * Fix an issue with adding broken Cordova plugins (#3914)
  * Validate that package names don't begin with a dash, end with a dot, or contain two dots in a row.
* `1.0.4-rc.2`:
  * Cordova is no longer entirely broken (that's in our QA process, we just hadn't gotten there yet :) )
  * Fix for using `blaze` package on the server
* `1.0.4-rc.1`:
  * Revert backwards-incompatible `Template.currentData`/`Template.parentData` change
  * Revert buggy websocket compression support
  * `Accounts.setPassword(u, p, { logout: false })` #3846 
  * Fix spacing in a tool message
* `1.0.4-rc.0`: initial release candidate

**Comment by stubailo** [comment]
The new `Session.set` syntax is documented, but in a way that is hard to find. I think it is worth the tradeoff because the only other option would be to make the function signature something like `Session.set(keyOrObject, [value])`

**Comment by glasser** [comment]
@stubailo Good point — I had only been looking at the api box in session.js and not the markdown file.  Sorry!

**Comment by glasser** [comment]
`1.0.4-rc.0` is out!  Test it!

**Comment by queso** [comment]
Can you add a bit about meteor --test being run once now? See https://github.com/meteor/meteor/pull/3793.

**Comment by LarsBuur** [comment]
Could you specify what the Cordova upgrades are about?

**Comment by glasser** [comment]
@queso Thanks, done.

@LarsBuur The [release notes](https://github.com/meteor/meteor/blob/release-1.0.4/History.md#meteor-mobile) cover that it in detail (thanks @Slava!)

**Comment by aminjam** [comment]
With production release of Mongo 3.0, It would be great to have the support in the next release.

**Comment by apacala** [comment]
@aminjam :+1:

**Comment by mquandalle** [comment]
I've updated LibreBoard to this latest release candidate. I believe you should emphasize the breaking change concerning the `Template.parentData()` value in event handlers, because if I wasn't following the development closely I would have wonder why a “patch” release broke my application — I use this feature in 3 different handlers in LibreBoard.

**Comment by emmanuelbuah** [comment]
Can I take it for a spin using ``` meteor run --release 1.0.4-rc.0 ```

**Comment by glasser** [comment]
@aminjam @apacala As I mentioned in the tasklist above was my plan, I've now run the test suite of `1.0.4-rc.0` against a MongoDB 3.0.0 backend. As I expected (because 3.0 actually doesn't have too many user-facing interface changes) it passed right out of the box!  I've updated History.md to note this (3cf30fbc1744d).  We're still going to ship 2.6 with the tool in 1.0.4, since our experience has been that most production users aren't running `*.0` versions of software, but hope to update soon, which is now being tracked in #3894. 

@mquandalle I'm going to check in with @stubailo about this.  My impression was that this was considered a bug fix, since it didn't make sense that `Template.currentData()` in event handlers didn't match its `this` data context.  But it is backwards-incompatible, so maybe it needs to be more highly advertised (eg with an upgraders notice?)

@emmanuelbuah Yes.

**Comment by stubailo** [comment]
@mquandalle that's a very good point. I wish there were better ways to notify people about small breaking changes, since bumping the major version of all of Blaze seems to be "overkill" for this instance even if it is technically correct. Maybe we need a log of breaking changes since the last major release somewhere? Upgrader could be good, but it might be hard to miss especially since in a collaborative project only one user will see the upgrade message.

**Comment by TimHeckel** [comment]
@glasser @stubailo - no issues have come up yet with rc0, and I've ran our app through its paces; I'm really excited for Mongo 3.0, so I'm very happy to hear the initial tests look good!

**Comment by glasser** [comment]
@mquandalle We're going to not make the backwards-incompatible change in 1.0.4.  @stubailo is probably just going to revert that part (or possibly we will come up with a way to do it not incompatibly).

We're going to keep the `instance()` change which was a bug-fix.

**Comment by glasser** [comment]
Also reverting websocket compression, which seems to be buggy in at least two ways.

**Comment by emgee3** [comment]
Oh, good, I was trying unsuccessfully to create a reproduction on the websocket compression errors I've been having.

**Comment by glasser** [comment]
@emgee3 What symptoms were you seeing?

**Comment by glasser** [comment]
and certainly if you manage to make a reproduction it'll help make a reproduction for our upstream library ;)

**Comment by emgee3** [comment]
Mostly disconnected websockets, with the following error:

    WebSocket connection to 'ws://nn.nn.nn.nn:3030/sockjs/488/ychl9h8v/websocket' failed: Could not decode a text frame as UTF-8.

which was caused by corrupted frames. I didn't see what exactly is happening, but the frames contain invalid JSON and mangled.

Interestingly, I don't see this in development, only production (which is self-hosted using `meteor build`). 

I can look into it a bit more if it helps.

**Comment by glasser** [comment]
`1.0.4-rc.1` published.  It reverts one buggy change and one backwards-incompatible change, and adds a simple PR #3846.

**Comment by atoi** [comment]
Blaze in 1.0.4 has an update [here](https://github.com/meteor/meteor/blob/8149538e9c3fa376642f19148956213247bfc956/packages/blaze/lookup.js#L70) which breaks meteor-ssr package. I get 'Template is not defined' error after the update. Should there be Blaze.Template instead of simply Template?

**Comment by glasser** [comment]
@atoi Is this with `1.0.4-rc.0` or `1.0.4-rc.1`?

**Comment by atoi** [comment]
I tried both. The result is the same.

**Comment by glasser** [comment]
Ah, I see.  c72f20c should fix this.

**Comment by nerdmed** [comment]
Hey @glasser  Cordova build for iOS is not working on a fresh meteor project. I have tried the simulator and xCode. Fails to start in both. Meteor 1.0.3.2 is working properly!
```
I will try to dig deeper, would be great to get this running soon as the new Cordova CLI has some important features!

xCode Log is the following:
2015-03-10 12:12:04.651 CordovaTest[16496:574362] Finished load of: file:///Users/username/Library/Developer/CoreSimulator/Devices/E356E5C2-C84A-4167-84CC-6D87F6F2ED70/data/Containers/Bundle/Application/DA85EDB4-F488-481A-A6DB-FA0DC07448EF/CordovaTest.app/www/index.html
2015-03-10 12:12:04.687 CordovaTest[16496:574362] METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///Users/username/Library/Developer/CoreSimulator/Devices/E356E5C2-C84A-4167-84CC-6D87F6F2ED70/data/Containers/Data/Application/AF08012D-CA0C-4672-86A5-B6997B08AF9B/Library/NoCloud/meteor/version
2015-03-10 12:12:04.687 CordovaTest[16496:574362] METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Couldn't load from the manifest, falling back to the bundled assets.
2015-03-10 12:12:04.688 CordovaTest[16496:574362] Error in Error callbackId: File335718168 : TypeError: undefined is not an object (evaluating 'httpd.startServer')
```

**Comment by rclai** [comment]
The fix for `Template.parentData` not working properly inside block helpers has been left intact right?

**Comment by glasser** [comment]
@rclai Correct.  Feel free to confirm this with rc.1 in case I'm wrong though!

**Comment by glasser** [comment]
@nerdmed Can you explain how to replicate this?  eg a precise set of commands that shows this.  eg, I did this and it worked OK:

```
glasser@perseid 1 ~/Scratch $ meteor  --release 1.0.4-rc.1 create --example localmarket
localmarket: created.

To run your new app:
  cd localmarket
  meteor
glasser@perseid 0 ~/Scratch $ cd localmarket/
glasser@perseid 0 ~/Scratch/localmarket $ meteor run ios
[[[[[ ~/Scratch/localmarket ]]]]]

=> Started proxy.
=> Started app on iOS Simulator.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by glasser** [comment]
Oh wait, I am actually replicating that. The app never made it beyond loading screen.

**Comment by glasser** [comment]
@nerdmed Are you seeing this with ios-device or just the simulator?

**Comment by glasser** [comment]
@nerdmed OK, there was a failed merge.  02770db1474ba445ba9fac7b824a86e093b60b2e should fix it. Going to build a new RC!

**Comment by glasser** [comment]
`1.0.4-rc.2` is out now, which should fix the issues reported by @atoi and @nerdmed 

The cordova issue turned out to be a merge error.  We would definitely have caught this before release as part of our Cordova QA process, which I was planning to start this afternoon anyway. But I really appreciate the early head's up from @nerdmed!

**Comment by nerdmed** [comment]
@glasser sorry for my late response different time zone :/
I can confirm that its working with RC2. Thanks a lot for your fast and effective reaction. I think helping to find this kind of issues is the least thing we can do to support you guys!

Unfortunately i have to point out some honest feedback because i really love what you guys are doing:
Meteor is the easiest way to develop Apps. The most common use case for Apps is on mobile devices. If Meteors vision is to be a real platform for developing application: mobile is one of the most important aspects, i feeling to be not being solved at this time. If you are aiming to have a little more complex hybrid app you want to have own native plugins that work well with the application. Writing plugins/packages for Cordova is an unreasonable demand at the current state. The Cordova Plugin System is way beyond the one meteor has. In fact there are some tiny improvements that could ease up development of cordova plugins with meteor. As a lot of us are JS-Devs we target to write Native Code for iOS in Swift. Currently there is no way to have local packages (in fact cordova has a way) and there is no way to set Deployment Targets to use Swift and some other advantages the Cordova CLI has to offer. I would consider to take this more serious as relates Issues aren't making progress and pushed to the community since October: #2925 and really overthink the way Cordova is implemented in meteor. Right now its not "the meteor way". Hope the feedback helps. peace

**Comment by glasser** [comment]
@nerdmed Thanks for your feedback.  Release 1.0.4 isn't really the best place to be tracking this, but it is heard.  One of our biggest goals for 2015 is [hiring more engineers](https://www.meteor.com/jobs) at MDG so that there can be more boxes in the "Present" column on https://trello.com/b/hjBDflxp/meteor-roadmap :)  Right now, we can only work on a subset of our projects at a time, but hopefully this won't be true soon!

**Comment by nerdmed** [comment]
@glasser sorry for that :) sounds like a good plan :+1:

**Comment by glasser** [comment]
`1.0.4-rc.3` is out, adding a bit of extra validation to package names and fixing an issue in Cordova around adding plugins which need configuration.

**Comment by rclai** [comment]
Are you guys also releasing the new logic solver, or is that a later release?

**Comment by glasser** [comment]
The logic solver is not going into 1.0.4, but it's on devel now!

**Comment by rclai** [comment]
Yeah, I saw, that's why I was wondering.

**Comment by glasser** [comment]
I've added prerelease docs to https://docs-104rc.meteor.com/

**Comment by glasser** [comment]
`1.0.4-rc.4` published, adding a little more validation to package names.

**Comment by faburem** [comment]
Cordova did not work for me with 1.0.4-rc.3 but it is now working with 1.0.4-rc.4. I'll keep testing this with all RCs and report my results since I am eager to push 1.0.4 to production for some of my projects. Keep up the good work guys!

**Comment by tdesc** [comment]
Same here. Cordova not working.
Using (built-in) Android SDK at /Users/----------/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/----------/.meteor/packages/meteor-tool/.1.0.42-rc.5.snwbsz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
Error while running for mobile platforms: Error running
/Users/----------/.meteor/packages/meteor-tool/.1.0.42-rc.5.snwbsz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Current working directory is not a Cordova-based project.


Error: Error running /Users/----------/.meteor/packages/meteor-tool/.1.0.42-rc.5.snwbsz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Current working directory is not a Cordova-based project.

**Comment by gabrielpoca** [comment]
There is an issue with the `cordova-buid-override`. Running a cold start application (with no `.local` folder) with `meteor run ios` will give the following error.

```
Error creating Cordova prject: Error running
/Users/gabriel/.meteor/packages/meteor-tool/.1.0.42-rc.5.av4l40++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
App id contains a reserved word, or is not a valid identifier.
```

Running again you get a different error:

```
Error while running for mobile platforms: Error running
/Users/gabriel/.meteor/packages/meteor-tool/.1.0.42-rc.5.av4l40++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Current working directory is not a Cordova-based project.
````

This error occurs because on `.meteor/local/cordova-build/config.xml` there is `com.id4yffpk1heln5x97y8k0`, that's not a valid id. Notice here that I have a `config.xml` file on my `cordova-buid-override` that should have replaced this one, but it's not happening.

Also, I noticed that if you're running version `1.0.3.2` (or something) and you update to this RC you don't get this issues (as long as you don't remove the `.local` folder). I know this would be slower, but from my experience with tools like `grunt-phonegap` I know that it's probably better to always remove the build directory before every run.

**Comment by glasser** [comment]
@gabrielpoca Can you show a full reproduction from scratch, with every command in order?

**Comment by Slava** [comment]
@gabrielpoca can you link to a page that describes what "valid id" is? I am confident that at least in Cordova 3.6 the string `com.id4yffpk1heln5x97y8k0` was a valid id.

**Comment by gabrielpoca** [comment]
@Slava and you're right. I was just reading the error message and showing what's on the config.xml at the time. Quick search turns into [this](https://www.mail-archive.com/issues@cordova.apache.org/msg37256.html), but I don't know if the regular expression what they expect. @glasser sure, I'll do that.

**Comment by stachrom** [comment]
xmlbuilder and meteor 1.0.4

@glasser I set up the repo : https://github.com/stachrom/meteor_1.0.4

ref: https://forums.meteor.com/t/help-test-release-candidates-for-meteor-1-0-4/896/34

**Comment by Slava** [comment]
@stachrom @glasser it could be because the name of the local package collides with the name of the core package that we already have in meteor/meteor: https://github.com/meteor/meteor/tree/devel/packages/xmlbuilder

**Comment by stachrom** [comment]
@Slava meteor version 1.0.3.2 with xmlbuilder version 2.4.5 is working fine. 
meteor version 1.0.3.2 with xmlbuilder version 2.6.2 (latest) does not work --> conflict: constraints on xmlbuilder cannot be satisfied.

in meteor 1.0.4 neither does work. (xmlbuilder 2.4.5 nor 2.6.2)

**Comment by stachrom** [comment]
@Slava  @glasser xmlbuilder solved. 
I just use the meteor internal package https://github.com/meteor/meteor/tree/devel/packages/xmlbuilder and throw my own xmlbuilder package over board.

Regards roman

**Comment by tdesc** [comment]
Problem get back. It is not fixed by remove .meteor/local/cordova-build and meteor remove-platform ios
Forced to downgrade to 1.0.3.2, create xcode project and upgrade to 1.0.4-rc.4.
I use cordova 4.3.0 and upgrade cordova platform update ios to cordova-ios@3.8.0

**Comment by glasser** [comment]
@tdesc Can you show a precise series of commands starting from an empty directory (perhaps including `git clone` if that's easy) that replicates the issue you're seeing?

**Comment by glasser** [comment]
`1.0.4-rc.5`, just released, fixes the ability of Cordova apps to access the server from the Android emulator (`meteor run android`).

**Comment by rclai** [comment]
How do you guys plan to revisit the `Template.currentData()` reversion? I do think that it should reflect what `this` should be.

**Comment by glasser** [comment]
@rclai Not decided as part of this release, but most likely we will try to make backwards-incompatible changes like that in either a way that is not backwards compatible (eg new function names/deprecate old ones), opt-in, or backwards-incompatibly but as part of a larger revamp that offers compelling reasons to put the time in to update your app.

**Comment by glasser** [comment]
`1.0.4-rc.6` partially reverts the no-multiple-colons-in-package-names change, and moves license files to a different place in the built tool (one file per license type).

**Comment by caioreis** [comment]
@glasser, I'm testing a real case here with template subscriptions. In my opinion it's taking too long to unsubscribe after the template is destroyed. It is not a bug, but maybe we can take a look at this?

**Comment by glasser** [comment]
@caioreis I'm in the process of releasing 1.0.4 now, so this won't affect 1.0.4, but please open a bug (following our [usual bug reporting guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor)) and we'll see if it calls for a 1.0.4.1.

**Comment by glasser** [comment]
1.0.4 is released!

Known slight issue: if you're going to http://docs.meteor.com (not https) it may not update you from 1.0.3.2 to 1.0.4 docs (issue with appcache vs force-ssl).  @n1mmy is dealing.

**Comment by jatsrt** [comment]
@gabrielpoca any update on your issue, after an update to 1.0.4 and clearing my .meteor/local I am getting>

Error creating Cordova prject: Error running /Users/jake/.meteor/packages/meteor-tool/.1.0.42.6fy9sm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
App id contains a reserved word, or is not a valid identifier.

**Comment by gabrielpoca** [comment]
@jatsrt I did have the time yet. I should be able to attempt to reproduce the error from scratch. For now you can change back to `1.0.3`, remove the `.meteor/local/cordova-build`, run `meteor run ios` (or something) and then go  to `1.0.4`. It should work.

**Comment by patrickml** [comment]
MUP Deployment is failing after upgrading to version 1.0.4

 ✘ Invoking deployment process: FAILED
        
        -----------------------------------STDERR-----------------------------------
        Dnode_root_dir=/root/.node-gyp/0.10.34',
        gyp info spawn args   '-Dmodule_root_dir=/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
        gyp info spawn args   '--depth=.',
        gyp info spawn args   '--no-parallel',
        gyp info spawn args   '--generator-output',
        gyp info spawn args   'build',
        gyp info spawn args   '-Goutput_dir=.' ]
        gyp info spawn make
        gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
        gyp info ok 
        npm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
        Latest deployment failed! Reverted back to the previous version.
        -----------------------------------STDOUT-----------------------------------
        inished
          COPY Release/bcrypt_lib.node
        make: Leaving directory '/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
        
        > fibers@1.0.5 install /opt/meteor/tmp/bundle/programs/server/node_modules/fibers
        > node ./build.js
        
        `linux-x64-v8-3.14` exists; testing
        Binary is fine; exiting
        underscore@1.5.2 node_modules/underscore
        
        eachline@2.3.3 node_modules/eachline
        └── type-of@2.0.1
        
        semver@4.1.0 node_modules/semver
        
        chalk@0.5.1 node_modules/chalk
        ├── ansi-styles@1.1.0
        ├── escape-string-regexp@1.0.3
        ├── supports-color@0.2.0
        ├── has-ansi@0.1.0 (ansi-regex@0.2.1)
        └── strip-ansi@0.3.0 (ansi-regex@0.2.1)
        
        source-map-support@0.2.8 node_modules/source-map-support
        └── source-map@0.1.32 (amdefine@0.1.0)
        
        fibers@1.0.5 node_modules/fibers
        Waiting for MongoDB to initialize. (5 minutes)
        connected
        meteor stop/waiting
        meteor start/running, process 471
        Waiting for 15 seconds while app is booting up
        Checking is app booted or not?
        meteor stop/waiting
        meteor start/running, process 531
        ----------------------------------------------------------------------------

**Comment by glasser** [comment]
@patrickml I think the proper place to file bugs in using MUP deployment is https://github.com/arunoda/meteor-up

If it turns out that there's an underlying Meteor core problem that's breaking MUP deployment, file a new bug that explains what has changed in Meteor to affect MUP.

**Comment by patrickml** [comment]
@glasser Thank you I have moved my issue over to MUP.

Also meteor update --patch doesnt work after you have upgraded to the newest version and then downgraded.

I.e.

Upgrade to 1.0.4

Downgrade to 1.0.3

try to patch it will failed because it says you already have the latest version

 A patch (Meteor 1.0.3.2) for your current release is available!
   Update this project now with 'meteor update --patch'.

Patricks-MBP:LF patricklewis$ meteor update --patch
The latest version of Meteor, 1.0.4.1, is already installed on this computer. Run 'meteor update' inside of a particular project directory to update that project to Meteor 1.0.4.1

**Comment by glasser** [comment]
It looks like you're not actually running it inside of an app directory.

**Comment by jatsrt** [comment]
@gabrielpoca Check out https://github.com/meteor/meteor/issues/3950 for a thread on this.

**Comment by gwendall** [comment]
I also get a "Error creating Cordova prject [...] App id contains a reserved word, or is not a valid identifier." when running the following on 1.0.4. Works fine on 1.0.3.

meteor create foo
meteor add-platform ios

**Comment by rteslaru** [comment]
Running into the same issue as @gwendall, "Error creating Cordova prject [...] App id contains a reserved word, or is not a valid identifier." on 1.0.4.1. Works fine on 1.0.3

**Comment by glasser** [comment]
Great, let's continue to track this in #3950 because 1.0.4 is now out.
