### ISSUE TITLE
Release 1.2.1 - Release candidate out!

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5478]
This is going to be a relatively small release with no huge headline features, just some nice improvements!

- Faster collection inserts on the server
- New `ecmascript-runtime` package to replace `ecmascript-collections`, which provides more ES2015 polyfills!
- Support for named pipes as a port in production mode, needed for IIS on Windows
- See more here: https://github.com/meteor/meteor/blob/release-1.2.1/History.md#v121-

Release branch is [`release-1.2.1`](https://github.com/meteor/meteor/tree/release-1.2.1).
Tasks are being tracked in the [Release 1.2.1 milestone](https://github.com/meteor/meteor/milestones/Release%201.2.1).

### Release candidate

Try the RC with `meteor --release 1.2.1-rc.4`!

We haven't done QA yet, but want to get this into people's hands ASAP.

### Todos

- [x] Update History.md
- [x] Establish what QA needs to be done
- [x] Add issues for documentation
- [x] Finish all tasks in 1.2.1 milestone
- [x] Add https://github.com/meteor/meteor/commit/c9297037900ecd43f8c267023a8736230506c6e7 to History.md - @glasser 

### QA to be done

- [x] Run package tests in all browsers to check new ES2015 polyfills - in particular, IE8/9.
- [x] Do Auth QA with Google to check that the loginHint option didn't break anything

**Comment by TomFreudenberg** [comment]
You may see the commit diffs via:

https://github.com/meteor/meteor/compare/release/METEOR@1.2.0.2...release-1.2.1

**Comment by stubailo** [comment]
Yep, I've already gone through all of them and updated History.md. Did I miss anything? https://github.com/meteor/meteor/blob/release-1.2.1/History.md#v121-

**Comment by TomFreudenberg** [comment]
As I checked too History.md now looks similar to the commit diff.

**Comment by stubailo** [comment]
I've published an RC: `1.2.1-rc.1`

Going to post on the forums now!

**Comment by TomFreudenberg** [comment]
Ok, thanks Sashko, I check that on our arm fork.

**Comment by stubailo** [comment]
Published a new RC, `1.2.1-rc.4`, because I screwed up the version numbers on the first one.

**Comment by TomFreudenberg** [comment]
Ok, but never mind, build process on arm was already successful with rc.1 - thats ok for my test, I will wait until next meteor 1.2.1 release to publish a new arm one on bintray. Thanks for info.

**Comment by stubailo** [comment]
OK, I think we've got all of the tasks in there. Going to release a new RC, then do a sanity check, and then push forward to the final release by the end of the day!

**Comment by TomFreudenberg** [comment]
Great, thanks for update. I will start my ARM engines and get them hot to build a new release as well when ready :+1:

**Comment by TomFreudenberg** [comment]
Hey Sashko ( @stubailo )

as I was notified you already created the new release tag

https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.2.1

May I already take that as the "final" new release although currently the new bundle is not available (I guess you are still in the build process?)

**Comment by stubailo** [comment]
Yep! Still building the installer files.

**Comment by TomFreudenberg** [comment]
:-) I am just uploading the arm7 bundles to bintray but will wait until you post the new official release until I update my default branch on the repo.

**Comment by stubailo** [comment]
Done! New Meteor installs now get 1.2.1, and I've redeployed the docs. Now I just need to update www.meteor.com and merge some branches.

**Comment by TomFreudenberg** [comment]
Nice, I am currently building last dev_bundle for armv6 on Raspi jessie - then also ready. I will push a twitter message later

**Comment by stubailo** [comment]
We did it! yay

**Comment by TomFreudenberg** [comment]
Me too, all is published and all links and README are updated as well. I will make a post this afternoon on twitter. Thanks for this issue to track the activities. Tom
