### ISSUE TITLE
Update the Meteor Guide to incorporate Meteor 1.3 improvements

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#5785]
- [ ] New React version has a different API. #6298 
- [ ] Tutorials should use ES2015 (including modules). #6303 
- [ ] Code snippets in the docs should use ES2015. #6305
- [x] Make a branch of the todos example app using the new module system.
- [x] Finalize list of guide articles to be released for Meteor 1.3.
- [x] Finish guide website with some tweaks, possibly get a CSS overhaul from @dominicnguyen.
- [x] Run through the guide to edit for typos and XXX comments.
- [x] Write guide intro page.

See https://github.com/meteor/guide/issues/219

**Comment by stubailo** [comment]
We're on it! Thanks for publishing the preview, super excited to hack it into the example app and see what it looks like!

**Comment by avital** [comment]
@stubailo Great! What else do you need from us to make this go as smoothly as possible?

**Comment by stubailo** [comment]
Since Meteor 1.3 is definitely not coming out before January, we've decided to polish up a few of the initial articles we have ready and release those as a holiday blog post. This means that integrating the module support might need to wait until January.

It would be nice if the testing functionality landed by then, so that we could keep the tests we have when we migrate the app.

If you want some ideas of stuff you could test to see if there are any blockers for the app, I could make a list (basically, make sure 1.3 works with some packages and patterns we are using)

**Comment by avital** [comment]
A list of things to test would help, yes.

We'll try to get testing ready early if possible.

**Comment by stubailo** [comment]
Two things I can see now, in addition to being able to run unit tests on modules to replace test-packages:

### Build plugin configuration via NPM

A couple build plugins, most notably the PostCSS plugin, rely on loading NPM packages during the build process. This means you need to be able to pass a config file to the plugin, and based on that config file the package loads some PostCSS plugins which are NPM packages and runs the build step. Currently this is done by using `meteorhacks:npm`, which always stores NPM packages in a specific place (the same place Meteor puts them if you `Npm.depends`). To get rid of meteorhacks:npm, we need to give build plugins a principled way to require NPM packages from the app, and make sure that these package migrate to the new system.

### Co-located files

Right now we have a [package for each "model"](https://github.com/meteor/todos/tree/master/packages/lists) - it has that collection, its schema, validations, methods, and publications. We need to be able to have an analogous concept in the new module system. I remember there was some discussion of requiring server-only files from common files, or the other way around; we basically need to do both. For example, we need to have DDPRateLimiter, which is server-only, accessible in the same place we define methods, which are common to client and server.

**Comment by tmeasday** [comment]
Splitting this out into smaller issues, I think the last few points are done.
