### ISSUE TITLE
Cordova improvements in Meteor 1.3

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#5786]
**A first beta release of the Cordova improvements for Meteor 1.3 is now available: https://github.com/meteor/meteor/issues/6050**

---

### Finish iOS plugin
- [x] Fix add bridging header script
- [x] Add more unit tests
- [x] Code cleanup and documentation
- [x] Use Git subtree for `GCDWebServer` dependency
- Set up CircleCI for plugin testing on iOS Simulator (see [this article](http://tsubik.com/blog/setting-up-circle-ci-for-cordova-plugin/)) [given up for now, couldn't get cordova-paramedic to work with the new cordova-ios platform]
- [x] Implement last known good version mechanism
- [x] Blacklist faulty versions?
- [x] Detect when a new app version has been installed and make sure the bundled version is used
- [x] Handle network errors while downloading, possibly automatic retry (using Meteor iOS backoff and network availability detection implementation?)
- [x] Find a solution for treating missing assets on the server as errors (instead of downloading and serving `index.html`)
- [x] Find a solution for making sure we've downloaded the right version of `index.html`
- [x] Safely resume downloads
- [x] Start background task when downloading so we have at least some time (OS dependent, currently 3 min) to finish downloads after the app goes into the background.
- [x] Avoid copying bundled assets (by allowing a parent asset bundle to be used to locate assets)
- [x] Resolve local server port conflicts with multiple active apps
- [x] Make sure we either use the same port when returning from the background, or reload using the new port
- [x] Avoid ROOT_URL changing to localhost after hot code push

#### Stretch goals:
- [ ] Implement native code compatibility check
- [x] Expose local file access

### Upgrade to  Cordova 5.4.1 / Cordova iOS 4.0
- [x] Either update the dev bundle or switch to using a `cordova` package
- [x] Use new Cordova platform API for logging, instead of the hacked approach in our current fork
- [x] Make `WKWebView` the default? That means dropping support for iOS 7, but Cordova itself doesn’t officially support it anymore either.
- [x] Fix launch images and app icons
- [x] Update access configuration in `mobile-config.js` to support modern whitelist mechanism
- [ ] Investigate if `browserpolicy` is enough to properly support CSP for Cordova

### Other
- [x] Test with iOS 8 (and decide whether we can still support iOS 7)
- [ ] Expose API to control when/if updates are downloaded and when they take effect (meteor/meteor#4876)
- [x] Check if setting the ETag header to the asset hash doesn't lead to problems elsewhere in Meteor or Galaxy (see https://github.com/meteor/meteor/issues/626)
- [x] Write design docs / README

### Upgrade to Cordova Android 5.0
- [ ] Investigate what is needed to support Android Marshmallow run-time permissions (meteor/meteor#5770)
- [x] Upgrade Crosswalk

### Other
- [ ] Update/rewrite Cordova self-tests
- [ ] Windows support (only if time permits)

**Comment by jamielob** [comment]
Just peed a little bit with excitement while reading this.

**Comment by avital** [comment]
@martijnwalraven, assuming your estimate for the iOS plugin is accurate, how many more weeks of work do you think it will take for releasing the new Android plugin?

**Comment by martijnwalraven** [comment]
2-3 weeks.

**Comment by Exilz** [comment]
Wonderful ! Looks like things are going in the right direction

**Comment by MoeBadr** [comment]
Really excited, Thanks for the hard work guys  !!

**Comment by chriswessels** [comment]
Brilliant news! Thanks @martijnwalraven

**Comment by Tibo46** [comment]
Great news !

**Comment by v3rron** [comment]
:clap: +1

**Comment by cwaring** [comment]
Thanks @martijnwalraven this is going to make a big difference, especially the WKWebView default! 🔥⚡

**Comment by DanielDornhardt** [comment]
Hi, please consider the point "Expose local file access" in the near future - we could really need a good way to access local files for our meteor cordova project. Essentially all cordova media plugins work by saving files to the local filesystem and pass the paths to the files. We're gonna try nate-strauser's solution for now, but I think it'd be great if there would be a nice and documented solution (eg. security concerns, which parts of the filesystem are accessible, maybe read / write / delete support).

https://github.com/meteor/meteor/issues/3799

**Comment by martijnwalraven** [comment]
A first beta release of the Cordova improvements for Meteor 1.3 is now available: https://github.com/meteor/meteor/issues/6050

**Comment by avital** [comment]
:fireworks:

**Comment by martijnwalraven** [comment]
A new 1.3 beta which combines modules, mobile, and testing is now available: https://github.com/meteor/meteor/issues/6266

Closing this issue to avoid confusion. Please open individual issues for any problems you encounter with Cordova in Meteor 1.3.
