### ISSUE TITLE
Run application node_modules using Node (without meteorInstall) on the server

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6398]
***3 Upvotes*** While it may be possible to make the `meteorInstall` module system behave sufficiently the same as Node in every way that matters, and while that is still our best option for `node_modules` on the client, on the server I believe we have a much easier option: just use Node!

This redesign will solve a wide range of remaining compatibility issues with server-side npm packages such as `pkginfo`, `github`, and `aws-sdk`.

Concrete steps:
- [x] Update [`PackageSource#_findSources`](https://github.com/meteor/meteor/blob/cfdcc37e0d34675acc9543eb88d4082aaf9b96f1/tools/isobuild/package-source.js#L1375) to include all files of any type in local `node_modules` directories.
- [x] Take precautions to ensure these files are not processed by compiler plugins, since `npm install` installs fully compiled files.
- [ ] <strike>In [`computeJSOutputFilesMap`](https://github.com/meteor/meteor/blob/cfdcc37e0d34675acc9543eb88d4082aaf9b96f1/tools/isobuild/compiler-plugin.js#L775-L784), instead of moving `node_modules` files into the bundle for the `modules` package, treat them as independent resources.</strike>
- [x] Obtain or create an instance of Node's `require` function that looks for packages using the correct path within the bundled app.
- [x] Teach `meteorInstall` to fall back to that `require` function when requiring application `node_modules`.
- [ ] Replace the `babel-runtime` Meteor package with the recommendation to `npm install babel-runtime@5`, since [this trick](https://github.com/meteor/meteor/blob/cfdcc37e0d34675acc9543eb88d4082aaf9b96f1/packages/babel-runtime/babel-runtime.js#L379-L395) probably will not work anymore.
- [x] Verify that #6313 is fixed.
- [x] Verify that #6173 is fixed.
- [x] Verify that #6165 is fixed.

cc @zol @glasser @sungwoncho

**Comment by stubailo** [comment]
:+1:

**Comment by stubailo** [comment]
> the recommendation to npm install babel-runtime@5

We can just put this in the `package.json` for new apps, and even add it via upgrader, right?

**Comment by benjamn** [comment]
@stubailo that's right, and we won't have issues like #6355 ever again

**Comment by tmeasday** [comment]
@benjamn this will resolve the question of whether people need to `npm install` in the tutorial, correct? (in the positive)

**Comment by benjamn** [comment]
The `babel-runtime` recommendation can wait. Otherwise this is fully implemented in `beta.16`, yay!
