### ISSUE TITLE
[third-party] `node-inspector` debug console has a bug.

### ISSUE THREAD

**Issue by codeHatcher** [meteor/meteor#8469]
Similar to #7991 and #7977

When I run with `meteor debug` and then go to `http://localhost:8080/?port=5959` upon opening the page I first see the following error in the console

`Network.loadResourceForFrontend failed.
Error: ENOENT: no such file or directory, open '/Users/avi/Code/transfs/.meteor/local/build/programs/server/profile.js.map`

when I try and type a variable in the console, I do not get any response (see gif)

![b3ebf061e4f3623a926c3a644e0cc30e](https://cloud.githubusercontent.com/assets/5360982/23722313/b5978af6-03f9-11e7-9acf-312b2c5429c1.gif)

Chrome: 56.0.2924.87 (64-bit)
OSX: 10.11.6 (15G1217)
Meteor: 1.4.2.7 and 1.4.2 and 1.4.2.3

**Comment by brucejo75** [comment]
This is a dup of #7991.  This is not a meteor bug, you can work around by patching node-inspector bug.  All described in #7991.

**Comment by codeHatcher** [comment]
@brucejo75 @abernix If this is not a bug then can we update the `meteor debug` part of the Meteor documentation to include those instructions for the patch? I have a few minutes of free time where I can update the Meteor documentation if someone will accept the PR

**Comment by codeHatcher** [comment]
This is the list of things I have tried so the next poor soul that comes across this doesn't have to read all the existing issues

- [x] Tried a `meteor reset` https://github.com/meteor/meteor/issues/7991#issuecomment-266388186 -didn't help
- [x] Tried the chrome reset https://github.com/meteor/meteor/issues/7977#issuecomment-259027995 -didn't help
- [ ] try a different chrome version 
- [ ] try the node-inspector 'patch' (don't want to do this because I assume with every upgrade and every app I have will have to be 'patched' https://github.com/node-inspector/node-inspector/issues/951#issuecomment-262441472

**Comment by abernix** [comment]
This is absolutely a bug with `node-inspector` and as @brucejo75 said, a duplicate of #7991 which explains the problem fairly clearly.  The same happens in `node-inspector` outside Meteor and will (eventually?) be fixed if/when `node-inspector` lands https://github.com/node-inspector/node-inspector/pull/955 and is reported in https://github.com/node-inspector/node-inspector/issues/903.

There are [easy work-arounds](https://github.com/meteor/meteor/issues/7991#issuecomment-266709459) in the other issue which will fix all versions of Meteor you currently have installed for all projects on that computer (just not new versions of Meteor until you run it again).

I realize it's been frustrating to solve for you, but considering the relatively low impact actually feel this is a really reasonable I'm not currently willing to fork `node-inspector` for the very few users this has affected.  Please rally behind the `node-inspector` issue/PR (linked above) and we'll happily bump to a stable release when it's fixed.  You can also consider using Safari (which still supports `.keyIdentifier`) if you absolutely need this console functionality right now.

I've temporarily updated the docs (with https://github.com/meteor/docs/commit/bf0b340a1815ed18a0463a17407fc721c1cfcbae) to help mitigate future confusion.

This can remain open for 60 days as a reminder to check and possibly remove the docs disclaimer/update `node-inspector`.

**Comment by codeHatcher** [comment]
I appreciate you updating the docs, thank you! I posted on the node-inspector issues as well hoping that they create a fix. It looks like it's sitting in a PR whose build failed because of a timeout (possibly not a build issue)

**Comment by abernix** [comment]
This should be fixed in Meteor 1.4.4.2!

**Comment by codeHatcher** [comment]
@abernix YAY

**Comment by aramk** [comment]
I'm still seeing this when using node-inspector@1.1.1 on Node 4.5.0 and Meteor 1.4.4.2 :(
